spring:
  datasource:
    url: ${CVP_DATABASE:jdbc:postgresql://103.130.213.253:5432/blog}
    username: ${CVP_USERNAME_DB:blog_datpt}
    password: ${CVP_PASSWORD_DB:blog_datpt123@}
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 259583618562-g1s3big00htpdfbj4ngmkmqlltgt97qg.apps.googleusercontent.com
            clientSecret: x8lusORzxUwBrbiPr7AVIfVH
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
application:
  datasource: # in addition to the standard spring.datasource properties
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true
  security:
    jwt:
      secret: 5867a8374e7c0f6284b177b48faf89e1c79d72d8
      token-validity-in-seconds: 86400 # 24 hour
      token-validity-in-seconds-for-remember-me: 2592000

  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect